"""Initial structure

Revision ID: 01
Revises: 
Create Date: 2024-04-07 16:19:29.233063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixeltoken',
    sa.Column('pixel', sa.String(length=1000), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pixel')
    )
    op.create_table('requestinfo',
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('pixel', sa.String(length=1000), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('fbclid', sa.String(length=1000), nullable=False),
    sa.Column('fbc', sa.String(length=1000), nullable=False),
    sa.Column('fbp', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'id')
    )
    op.create_index(op.f('ix_requestinfo_ip_address'), 'requestinfo', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requestinfo_ip_address'), table_name='requestinfo')
    op.drop_table('requestinfo')
    op.drop_table('pixeltoken')
    # ### end Alembic commands ###
