"""Initial structure1

Revision ID: 01
Revises: 
Create Date: 2024-05-01 23:46:56.671542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activitylog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("pixel", sa.String(length=30), nullable=False),
        sa.Column("fbclid", sa.String(length=1000), nullable=False),
        sa.Column("fbc", sa.String(length=1000), nullable=False),
        sa.Column("fbp", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sub_id", sa.String(length=50), nullable=False),
        sa.Column("flow", sa.String(length=255), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activitylog_ip_address"), "activitylog", ["ip_address"], unique=True)
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application", sa.String(length=250), nullable=False),
        sa.Column("url", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_application_application"), "application", ["application"], unique=False)
    op.create_table(
        "flowparams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flow", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=100), nullable=True),
        sa.Column("from_who", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flowparams_flow"), "flowparams", ["flow"], unique=False)
    op.create_table(
        "pixeltoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pixel", sa.String(length=30), nullable=False),
        sa.Column("token", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pixeltoken_pixel"), "pixeltoken", ["pixel"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pixeltoken_pixel"), table_name="pixeltoken")
    op.drop_table("pixeltoken")
    op.drop_index(op.f("ix_flowparams_flow"), table_name="flowparams")
    op.drop_table("flowparams")
    op.drop_index(op.f("ix_application_application"), table_name="application")
    op.drop_table("application")
    op.drop_index(op.f("ix_activitylog_ip_address"), table_name="activitylog")
    op.drop_table("activitylog")
    # ### end Alembic commands ###
