version: '3.9'

services:
  db:
    container_name: fb_postgresql
    image: postgres:16.2-alpine3.18
    restart: always
    hostname: postgresql
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - fb_pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_NAME}
      interval: 2s
      timeout: 3s
      retries: 40
    networks:
      - backend

  backend:
    build: ../.
    container_name: fb_app
    restart: always
    # image: ridpfrep/fb_project:latest
    volumes:
      - logs_volume:/app/logs
    ports:
      - "5000:7070"
    env_file: ../.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - backend

volumes:
  fb_pgdata:
  logs_volume:

networks:
  backend:
    name: backend
    